### ISSUE TITLE
JL数据集可以发一下吗？

### ISSUE THREAD

**Issue by long123524** [weiAI1996/CdSC#1]

**Comment by weiAI1996** [comment]
你可以通过百度网盘下载
链接：https://pan.baidu.com/s/1wl4pNiQHEB-H_7YIYbTjpg&nbsp;
提取码：nwpu





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiAI1996/CdSC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月7日(星期二) 晚上9:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[weiAI1996/CdSC] JL数据集可以发一下吗？ (Issue #1)
